<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="MockResponses\AirIndia\AirIndia.json" />
    <None Remove="MockResponses\AirIndia\AirIndiabookFlight.json" />
    <None Remove="MockResponses\AirIndia\AirIndiabookingDetails.json" />
    <None Remove="MockResponses\AirIndia\AirIndiaflightCost.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="MockResponses\BritishAirlines\BritishAirlines.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="MockResponses\BritishAirlines\BritishAirlinesbookFlight.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="MockResponses\BritishAirlines\BritishAirlinesbookingDetails.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="MockResponses\BritishAirlines\BritishAirlinesflightCost.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="MockResponses\Emirates\Emirates.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="MockResponses\Emirates\EmiratesbookFlight.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="MockResponses\Emirates\EmiratesbookingDetails.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="MockResponses\Emirates\EmiratesflightCost.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="MockResponses\AmericanAirlines\AmericanAirlines.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="MockResponses\AmericanAirlines\AmericanAirlinesbookFlight.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="MockResponses\AmericanAirlines\AmericanAirlinesbookingDetails.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="MockResponses\AmericanAirlines\AmericanAirlinesflightCost.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="MockResponses\AirIndia\AirIndia.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="MockResponses\AirIndia\AirIndiabookFlight.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="MockResponses\AirIndia\AirIndiabookingDetails.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="MockResponses\AirIndia\AirIndiaflightCost.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
